
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[221] =
    {   0,
        0,    0,   81,   79,   78,   77,   67,   72,   74,   70,
       45,   53,   69,   58,   59,   43,   39,   63,   41,   64,
       44,   75,   68,   62,   46,   48,   47,   79,   76,   60,
       71,   61,   73,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       65,   56,   66,   50,   54,   40,   42,   75,   51,   49,
       52,   57,   76,    0,   76,   76,   76,   76,   76,   76,
        8,   76,   76,   76,   76,   76,   76,   76,   16,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   55,    0,   76,   76,   76,   76,

       76,   76,   76,   76,   76,   76,   76,   14,   76,   76,
       17,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
        0,    1,   76,    3,    4,   76,   76,   76,   76,   11,
       10,   76,   76,   76,   15,   18,   34,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   30,   76,   76,    0,    2,    5,   76,   76,   76,
       76,   13,   76,   76,   76,   76,   37,   21,   76,   76,
       76,   76,   76,   76,   76,   28,   76,   76,   32,    0,
       76,   76,    9,   12,   76,   35,   76,   20,   22,   23,

       24,   25,   26,   38,   76,   76,   76,   33,   76,    7,
       36,   76,   27,   76,   76,    6,   19,   29,   31,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   27,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   29,   30,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   26,   41,   42,   43,   44,
       45,   46,   26,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    2,    2,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[222] =
    {   0,
        0,    0,  226,  227,  227,  227,  202,  227,  227,  227,
      227,  215,  227,  227,  227,  227,  209,  227,  206,  227,
      227,  202,  227,  227,  197,  196,  195,  197,    0,  227,
      227,  227,  189,  165,  167,   27,   24,   20,   25,  168,
       24,  167,  179,  163,  173,   40,  154,  163,  161,  166,
      227,  147,  227,  227,  227,  227,  227,  184,  227,  227,
      227,  227,    0,  170,  152,  164,  151,  166,  153,  159,
      145,  146,  143,  143,  146,  143,  142,  139,    0,  138,
      142,  145,  144,   27,  151,  137,   40,   43,  141,  132,
      133,   37,   41,  138,  227,  143,  131,  143,  138,  126,

       38,  140,  138,  134,  126,  132,  135,    0,  126,  120,
        0,  126,  119,  118,  121,  110,  115,  111,  113,  120,
      106,  104,  104,  103,  115,  105,  109,  113,  115,  104,
      104,    0,  103,    0,    0,   94,  102,   91,   98,    0,
        0,   92,   89,   93,    0,    0,    0,   87,   87,   87,
       96,   83,   95,   85,   89,   94,   93,   90,   90,   80,
       85,    0,   73,   85,   84,    0,    0,   75,   76,   81,
       72,    0,   66,   77,   64,   68,    0,    0,   76,   73,
       75,   59,   68,   63,   69,    0,   60,   63,    0,   67,
       51,   51,    0,    0,   62,    0,   62,    0,    0,    0,

        0,    0,    0,    0,   60,   60,   51,  227,   55,    0,
        0,   41,    0,   49,   46,    0,    0,    0,    0,  227,
       61
    } ;

static yyconst flex_int16_t yy_def[222] =
    {   0,
      220,    1,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  221,  220,
      220,  220,  220,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  221,  220,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  220,  220,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      220,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  220,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  220,
      221,  221,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  221,  221,  221,  221,  221,  221,  220,  221,  221,
      221,  221,  221,  221,  221,  221,  221,  221,  221,    0,
      220
    } ;

static yyconst flex_uint16_t yy_nxt[286] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   29,   41,
       29,   42,   43,   29,   29,   44,   45,   46,   47,   48,
       49,   50,   29,   29,   29,   51,   52,   53,   67,   70,
       79,   72,   63,   73,  115,   68,   75,   80,   71,   76,
       77,   69,   74,   85,  121,  116,  126,  119,   86,   87,
      128,  219,  129,  218,  127,  136,  137,  217,   88,  122,
      216,   89,  215,   90,  120,  214,  213,  212,  211,  210,

      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      159,  158,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  135,  134,  133,  132,  131,  130,  125,  124,
      123,  118,  117,  114,  113,  112,  111,  110,  109,  108,
      107,  106,  105,  104,  103,  102,  101,  100,   99,   98,

       97,   96,   58,   95,   94,   93,   92,   91,   84,   83,
       82,   81,   78,   66,   65,   64,   62,   61,   60,   59,
       58,   57,   56,   55,   54,  220,    3,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220
    } ;

static yyconst flex_int16_t yy_chk[286] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   36,   37,
       41,   38,  221,   38,   84,   36,   39,   41,   37,   39,
       39,   36,   38,   46,   88,   84,   92,   87,   46,   46,
       93,  215,   93,  214,   92,  101,  101,  212,   46,   88,
      209,   46,  207,   46,   87,  206,  205,  197,  195,  192,

      191,  190,  188,  187,  185,  184,  183,  182,  181,  180,
      179,  176,  175,  174,  173,  171,  170,  169,  168,  165,
      164,  163,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  144,  143,  142,  139,
      138,  137,  136,  133,  131,  130,  129,  128,  127,  126,
      125,  124,  123,  122,  121,  120,  119,  118,  117,  116,
      115,  114,  113,  112,  110,  109,  107,  106,  105,  104,
      103,  102,  100,   99,   98,   97,   96,   94,   91,   90,
       89,   86,   85,   83,   82,   81,   80,   78,   77,   76,
       75,   74,   73,   72,   71,   70,   69,   68,   67,   66,

       65,   64,   58,   52,   50,   49,   48,   47,   45,   44,
       43,   42,   40,   35,   34,   33,   28,   27,   26,   25,
       22,   19,   17,   12,    7,    3,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
enum yytokentype {
	CONSTANT =1,
	KEYWORD =2,
	OPERATION=3,
	IDENTIFICATOR=4,
	STRING = 5,
	SYMBOL =6,
	SALTO = 7,
	BLANCO=8,
	EOL = 9,
	ERROR = 10,
	GREATEREQUAL = 11,
	LESSEQUAL = 12,
	LESSTHAN = 13,
	GREATERTHAN = 14,
	LEFTBRACKET = 15,
	RIGHTBRACKET = 16,
	DOLLAR = 17,
	MODULE = 18,
	AMPERSAND = 19,
	UNDERSCORE = 20,
	AND = 21,
	NUM = 22,
	BACKSLASH = 23,
};
int yylval;
FILE* beamerFile;
int totalKeyword;
int totalOperation;
int totalSymbol;
int totalConstant;
int totalIdentificator;
int totalTokens;
int totalError;
#line 636 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 38 "scanner.l"


#line 857 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 221 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 227 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 40 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "scanner.l"
{return KEYWORD;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "scanner.l"
{ return MODULE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "scanner.l"
{ return LESSTHAN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "scanner.l"
{ return GREATERTHAN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "scanner.l"
{ return LESSEQUAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "scanner.l"
{ return GREATEREQUAL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 93 "scanner.l"
{ return AMPERSAND; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "scanner.l"
{ return AND; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "scanner.l"
{ return OPERATION;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "scanner.l"
{ return OPERATION; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 99 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 101 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "scanner.l"
{ return LEFTBRACKET; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "scanner.l"
{ return RIGHTBRACKET; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 108 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 110 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 111 "scanner.l"
{ return DOLLAR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 112 "scanner.l"
{ return BACKSLASH; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 113 "scanner.l"
{ return SYMBOL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 114 "scanner.l"
{ return UNDERSCORE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 115 "scanner.l"
{ return NUM;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 118 "scanner.l"
{ yylval = atoi(yytext); return CONSTANT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 120 "scanner.l"
{return IDENTIFICATOR;}
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 122 "scanner.l"
{ return SALTO; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 124 "scanner.l"
{ return BLANCO; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 126 "scanner.l"
{ return EOL;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 128 "scanner.l"
{ return ERROR;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 130 "scanner.l"
ECHO;
	YY_BREAK
#line 1319 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 221 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 221 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 220);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 130 "scanner.l"



void startBeamer(){
	beamerFile = fopen( "beamer.tex", "w+" );
	fprintf(beamerFile,"\\documentclass{beamer} \n");
	fprintf(beamerFile, "\\usetheme[]{Feather} \n" );
	fprintf(beamerFile, "\\usecolortheme{beaver} \n" );
	fprintf(beamerFile, "\\usepackage{color} \n" );
	fprintf(beamerFile, "\\usepackage[T1]{fontenc} \n" );
	fprintf(beamerFile, "\\usepackage[utf8]{inputenc} \n" );
	fprintf(beamerFile, "\\let\\Tiny=\\tiny \n" );
	fprintf(beamerFile, "\\usepackage{pgfplots}\n" );
	fprintf(beamerFile,"\\pgfplotsset{compat=newest,compat/show suggested version=false} \n");
	fprintf(beamerFile, "\\usepackage{pgf-pie}\n" );
	fprintf(beamerFile, "\\usepackage{tikz}\n" );
	fprintf(beamerFile, "\\usepackage{hyperref}\n" );
	fprintf(beamerFile, "\\usepackage{graphicx}\n" );
fprintf(beamerFile, "\\graphicspath{ {Feathergraphics//} }\n" );



fprintf(beamerFile, "\\newcommand{\\chref}[2]{ \\href{#1}{{\\usebeamercolor[bg]{Feather}#2}}} \n" );
fprintf(beamerFile, "\\title[] {       \\textbf{Proyecto 1 - Analizador Léxico}}\\subtitle[Analizador Léxico]{\\textbf{Compiladores e Intérpretes}}\\author[Luis Rojas - Ariel Montero - Bryan Jiménez]{      Luis Rojas - Ariel Montero - Bryan Jiménez \\\\{\\ttfamily IS 2017}}\\institute[]{Instituto Tecnológico de Costa Rica\\\\}\\date{\\today} \n" );



	
	fprintf(beamerFile,"\\begin{document} \n");


fprintf(beamerFile, " {\\1 \\begin{frame}[plain,noframenumbering] \\titlepage \\end{frame}} \\begin{frame}{Contenido}{} \\tableofcontents \\end{frame} \n");


	fprintf(beamerFile,"\\section{Explicación General}");
	fprintf(beamerFile,"\\subsection{Datos Generales}");

	fprintf(beamerFile,"\\begin{frame}[allowframebreaks] \n");
	fprintf(beamerFile,"\\frametitle{Datos Generales} \n \n");
fprintf(beamerFile,"\\begin{block}{\\textbf{Definiciones}} \n");


	fprintf(beamerFile,"\\textbf{Token}: Familia de lexemas, es una categoría donde se clasifican los lexemas.\\newline \n");
	fprintf(beamerFile,"\\textbf{Lexema}: Ejemplo particular de la variable.\\newline \n");

	fprintf(beamerFile,"\\textbf{Hilera}: Cadenas de texto generalmente marcadas entre comillas. \\newline \n");
	fprintf(beamerFile,"\\textbf{Constante}: Valor que no cambia, ya esta definido. \\newline \n");
	fprintf(beamerFile,"\\textbf{Identificadores}: Conjunto de caracteres alfanuméricos que sirven para identificar las entidades del programa  \\newline \n");

fprintf(beamerFile,"\\end{block}\n");
fprintf(beamerFile,"\\begin{block}{\\textbf{Definiciones}} \n");


	fprintf(beamerFile,"\\textbf{Palabras reservadas}: Palabras que son usadas por el lenguaje y no pueden modificarse ni su función. \\newline \n");
	fprintf(beamerFile,"\\textbf{Símbolos especiales}: Símbolos con significado especial en el lenguaje por lo que no se pueden usar para  otro proposito.\\newline \n");
	fprintf(beamerFile,"\\textbf{Operadores}: Símbolos utilizados para realixar operaciones lógicas y matemáticas. \\newline \n");
	
	
fprintf(beamerFile,"\\end{block}\n");
	fprintf(beamerFile,"\\end{frame} \n");



	fprintf(beamerFile,"\\subsection{Scanning}");

fprintf(beamerFile,"\\begin{frame} \n");
fprintf(beamerFile,"\\frametitle{Scanning} \n \n");
fprintf(beamerFile,"\\includegraphics[width=\\textwidth]{scan}");
fprintf(beamerFile,"\\end{frame} \n");


	fprintf(beamerFile,"\\begin{frame}[allowframebreaks] \n");
	fprintf(beamerFile,"\\frametitle{Scanning} \n \n");
	fprintf(beamerFile,"Un analizador léxico o scanner es la primera fase de un compilador y consistente en un programa que recibe como entrada el código fuente de otro programa (secuencia de caracteres) y produce una salida compuesta de tokens (componentes léxicos) o símbolos. Estos tokens sirven para una posterior etapa del proceso de traducción, siendo la entrada para el analizador sintáctico o parser. La especificación de un lenguaje de programación suele incluir un conjunto de reglas que definen el léxico. Estas reglas consisten comúnmente en expresiones regulares que indican el conjunto de posibles secuencias de caracteres que definen un token o leóxema.");
	fprintf(beamerFile,"\\end{frame} \n");




	fprintf(beamerFile,"\\subsection{Flex}");


fprintf(beamerFile,"\\begin{frame} \n");
fprintf(beamerFile,"\\frametitle{Flex} \n \n");
fprintf(beamerFile,"\\includegraphics[width=\\textwidth]{flex}");
fprintf(beamerFile,"\\end{frame} \n");


	fprintf(beamerFile,"\\begin{frame}[allowframebreaks] \n");
	fprintf(beamerFile,"\\frametitle{Flex} \n \n");
	fprintf(beamerFile,"Flex es una heramienta para generar scanners, flex lee las entradas para tener una descripción del scanner que debe generar. La descripción se realiza en pares de expresiones regulares y cóodigo en C, que se llaman reglas. Genera una salida en un archivo en C 'lex.yy.c' que define a una rutima 'yylex()'. Este archivo es compilado y unido con la librería '-lfl' para generar el ejecutable. Cuando se llama al ejecutable este analiza la entrada por ocurrencias de las expresiones regulares, cuando encuentra una ejecuta el código correspondiente en C.");

	fprintf(beamerFile,"\\end{frame} \n");




	fprintf(beamerFile,"\\section{Programa Fuente}");
	fprintf(beamerFile,"\\begin{frame}[allowframebreaks] \n");
	fprintf(beamerFile,"\\frametitle{Programa Fuente} \n");
}


void endBeamer(){


fprintf(beamerFile,"{\\1\\begin{frame}[plain,noframenumbering] \\finalpage{\\textbf{MUCHAS GRACIAS}}\\end{frame}} \n");

  fprintf(beamerFile,"\\end{document} \n");
  fclose(beamerFile);
  system("pdflatex beamer.tex");
  remove("tmp.c");
  remove("listo.c");
  system("evince --fullscreen beamer.pdf");
}

void writeBeamer(char *_color, char *_word){
  fprintf(beamerFile, "\\textcolor{%s}{ %s } \n", _color, _word);
}

void createHistogram(){
  fprintf(beamerFile,"\\section{Diagramas}");
  fprintf(beamerFile,"\\subsection{Histograma}");
  fprintf(beamerFile,"\\end{frame} \n");
  fprintf(beamerFile,"\\begin{frame} \n");
  fprintf(beamerFile,"\\frametitle{Histograma} \n");
  fprintf(beamerFile,"\\begin{tikzpicture} \n");
  fprintf(beamerFile,"\\begin{axis}[");
  fprintf(beamerFile,"ybar,enlargelimits=0.15,");
  fprintf(beamerFile,"legend style={at={(0.5,-0.2)}, anchor=north,legend columns=-1}, ylabel={Cant. Lexemas},");
  fprintf(beamerFile,"symbolic x coords={Palabra Clave,Operadores,Símbolos,Constantes,Identificadores,Errores},");
  fprintf(beamerFile,"xtick=data,nodes near coords,nodes near coords align={vertical},");
  fprintf(beamerFile,"x tick label style={rotate=45,anchor=east},] \n");
  fprintf(beamerFile,"\\addplot[ybar,fill=orange] coordinates {(Palabra Clave,%i) (Operadores,%i)",totalKeyword,totalOperation);
  fprintf(beamerFile,"(Símbolos,%i) (Constantes,%i) (Identificadores,%i) (Errores,%i)}; \n",totalSymbol,totalConstant,totalIdentificator,totalError);
  fprintf(beamerFile,"\\end{axis} \n");
  fprintf(beamerFile,"\\end{tikzpicture} \n");
  fprintf(beamerFile,"\\end{frame} \n");
}


void createPastel(int _symbol,int _keyword,int _operation,int _constant,int _identificator,int _error){


fprintf(beamerFile,"\\subsection{Diagrama Pastel}");
fprintf(beamerFile,"\\begin{frame}{Diagrama Pastel} \n");
fprintf(beamerFile,"\\def\\angle{0}");
fprintf(beamerFile,"\\def\\radius{2}");
fprintf(beamerFile,"\\def\\labelradius{3}");
fprintf(beamerFile,"\\def\\cyclelist{{\"green\",\"purple\",\"red\",\"blue\",\"orange\",\"olive\"}}");
fprintf(beamerFile,"\\centering");
fprintf(beamerFile,"\\newcount\\cyclecount \\cyclecount=-1");
fprintf(beamerFile,"\\newcount\\ind \\ind=-1");
fprintf(beamerFile,"\\begin{tikzpicture}");
fprintf(beamerFile,"\\foreach \\percent/\\name in {");
fprintf(beamerFile,"%i/P.Clave.,",_keyword);
fprintf(beamerFile,"%i/Opera.,",_operation);
fprintf(beamerFile,"%i/Símb.,",_symbol);
fprintf(beamerFile,"%i/Const.,",_constant);
fprintf(beamerFile,"%i/Ident.,",_identificator);
fprintf(beamerFile,"%i/Error",_error);
fprintf(beamerFile,"} {\\ifx\\percent\\empty\\else");
fprintf(beamerFile,"\\global\\advance\\cyclecount by 1");
fprintf(beamerFile,"\\global\\advance\\ind by 1");
fprintf(beamerFile,"\\ifnum6<\\cyclecount");
fprintf(beamerFile,"\\global\\cyclecount=0");
fprintf(beamerFile,"\\global\\ind=0");
fprintf(beamerFile,"\\fi");
fprintf(beamerFile,"\\pgfmathparse{\\cyclelist[\\the\\ind]}");
fprintf(beamerFile,"\\edef\\color{\\pgfmathresult}");
fprintf(beamerFile,"\\draw[fill={\\color!50},draw={\\color}] (0,0) -- (\\angle:\\radius) arc (\\angle:\\angle+\\percent*3.7:\\radius) -- cycle;");
fprintf(beamerFile,"\\draw[draw=gray, shorten >=2pt] (\\angle+0.5*\\percent*3.7:\\labelradius) node {\\name~[\\percent\\%%]} edge (\\angle+0.5*\\percent*3.7:\\radius);");
fprintf(beamerFile,"\\pgfmathparse{\\angle+\\percent*3.7}");
fprintf(beamerFile,"\\xdef\\angle{\\pgfmathresult}");
fprintf(beamerFile,"\\fi};");
fprintf(beamerFile,"\\end{tikzpicture}");
fprintf(beamerFile,"\\end{frame} \n");
}

void getPorcentage(){
	int symbol = (totalSymbol * 100)/ totalTokens;
	int keyword= (totalKeyword * 100)/ totalTokens;
	int operation= (totalOperation * 100)/ totalTokens;
	int constant= (totalConstant * 100)/ totalTokens;
	int identificator= (totalIdentificator * 100)/ totalTokens;
	int error = (totalError * 100)/ totalTokens;

	createPastel(symbol,keyword,operation,constant,identificator,error);
}

void main(int argc, char **argv)
{
	int tok;
	yyin = fopen ("listo.c","r+");
  	startBeamer();
	tok = yylex();

	while(tok!=EOL){

		switch (tok){
			case CONSTANT:
				writeBeamer("blue", yytext);
        		totalConstant++;
				totalTokens++;
				break;
			case KEYWORD:
				writeBeamer("purple", yytext);
        		totalKeyword++;
				totalTokens++;
				break;
			case OPERATION:
        		writeBeamer("green", yytext);
        		totalOperation++;
				totalTokens++;
        		break;
			case GREATEREQUAL:
				fprintf(beamerFile, "\\textcolor{%s}{%s} \n", "green","$>=$");
				totalOperation++;
				totalTokens++;
				break;
			case GREATERTHAN:
				fprintf(beamerFile, "\\textcolor{%s}{\\textgreater} \n", "green");
				totalOperation++;
				totalTokens++;
				break;
			case LESSEQUAL:
				fprintf(beamerFile, "\\textcolor{%s}{%s} \n", "green","$<=$");
				totalOperation++;
				totalTokens++;
				break;
			case LESSTHAN:
				fprintf(beamerFile, "\\textcolor{%s}{\\textless} \n", "green");
				totalOperation++;
				totalTokens++;
				break;
			case MODULE:
				fprintf(beamerFile, "\\textcolor{%s}{\\%%} \n", "green");
				totalOperation++;
				totalTokens++;
				break;
			case AMPERSAND:
				fprintf(beamerFile, "\\textcolor{%s}{\\&} \n", "green");
				totalOperation++;
				totalTokens++;
				break;
			case AND:
				fprintf(beamerFile, "\\textcolor{%s}{\\&\\&} \n", "green");
				totalOperation++;
				totalTokens++;
				break;
			case SALTO:
        		fprintf(beamerFile,"\\newline \n");
				break;
			case IDENTIFICATOR:
        		writeBeamer("orange", yytext);
        		totalIdentificator++;
				totalTokens++;
        		break;
			case SYMBOL:
		        writeBeamer("olive", yytext);
		        totalSymbol++;
				totalTokens++;
        		break;
        	case BACKSLASH:
				fprintf(beamerFile, "\\textcolor{%s}{\\textbackslash} \n", "olive");
				totalSymbol++;
				totalTokens++;
				break;
			case UNDERSCORE:
				fprintf(beamerFile, "\\textcolor{%s}{\\_ } \n", "olive");
				totalSymbol++;
				totalTokens++;
				break;
			case NUM:
				fprintf(beamerFile, "\\textcolor{%s}{\\# } \n", "olive");
				totalSymbol++;
				totalTokens++;
				break;
			case DOLLAR:
			    fprintf(beamerFile, "\\textcolor{%s}{\\$ } \n", "olive");
			    totalSymbol++;
				totalTokens++;
	      		break;
			case RIGHTBRACKET:
	      		fprintf(beamerFile, "\\textcolor{%s}{\\} } \n", "olive");
	      		totalSymbol++;
				totalTokens++;
	      		break;
			case LEFTBRACKET:
				fprintf(beamerFile, "\\textcolor{%s}{ \\{ } \n", "olive");
		    	totalSymbol++;
				totalTokens++;
		    	break;
			case ERROR:
				writeBeamer("red", "Symbol not identified");
				totalError++;
				break;
			default:
				break;
		}
		tok = yylex();
	}
  	createHistogram();
	getPorcentage();
  	endBeamer();
}

